config/routes.rb
StockForecaster::Application.routes.draw do

  get "search/fb"
  get "search/aapl"
  get "search/goog"
  get "portfolio/new"
  get "portfolio/add"
  get "portfolio/remove"
  match "portfolio/add" => 'portfolio#index', :via => :post
  match "search/goog" => 'search#index', :via => :post
  match "search/aapl" => 'search#index', :via=> :post
  match "search/fb" => 'search#index', :via=> :post
  get "faq/index"
  get "faq" => 'faq#index'
  get "news/index"
  get "news" => 'news#index'
  get "portfolio/index"
  get "portfolio" => 'portfolio#index'
  get "home" => 'welcome#index'
  get "welcome/index"

  root 'welcome#index'

end

app/models/portfolio.rb
class Portfolio < ActiveRecord::Base
	attr_accessible :ticker, :quantity

	validates :todo_item, presence: true

	@portfolio = Portfolio.new
end

app/models/search.rb
class Search < ActiveRecord::Base
	attr_accessible :ticker

	validates :ticker, presence: true, :on => [:create]

	@search = Search.new
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
end

app/controllers/faq_controller.rb
class FaqController < ApplicationController
  def index
  end
end

app/controllers/news_controller.rb
class NewsController < ApplicationController
  def index
  end
end

app/controllers/portfolio_controller.rb
class PortfolioController < ApplicationController

  	def index
  		@portfolio = Portfolio.all
  		@new_portfolio = Portfolio.new
  		render "index"
  	end

  	def new
  		@portfolio = Portfolio.new
  		@portfolio.save

  	end

  	def add
  		@portfolio = Portfolio.create(:ticker => params[:portfolio][:ticker], :quantity => params[:portfolio][:quantity]);

  		redirect_to :action => 'index'
  	end

  	def remove
  	end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def fb
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  	def index
  	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/faq_helper.rb
module FaqHelper
end

app/helpers/news_helper.rb
module NewsHelper
end

app/helpers/portfolio_helper.rb
module PortfolioHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/faq/index.html.erb
<h1>Faq#index</h1>
<p>Find me in app/views/faq/index.html.erb</p>

app/views/layouts/_header.html.erb
		<nav class="top-bar" data-topbar>
			<ul class="title-area">
				<li class="name">
					<h1><%= link_to "Home", root_path %></h1>
				</li>
			</ul>

			<!-- Navi Bar Section -->
			<section class="top-bar-section">

				<!-- Navi Links -->
				<ul class="left">
					<li><%= link_to "My Portfolio", portfolio_path %></a></li>
					<li><%= link_to "News", news_path %></a></li>
					<li><%= link_to "FAQ", faq_path %></a></li>
				</ul>

			<%= form_tag(:url => {:action => "search"}, :method => 'post') do %>
				<ul class="right">
					<li class="has-form">
						<div class="row collapse">
								<div class="large-8 small-9 columns">
									<%= text_field_tag(:search, params[:search], :id => 'ticker', :placeholder => 'Stock Ticker') %>
        						</div>
								<div class="large-4 small-3 columns">
									<a href="/search" class="button">Search</a>
								</div>
			<% end %>
							<!-- Dropdown Account Menu -->
								<li class="has-dropdown">
        							<a href="#">My Account</a>
        							<ul class="dropdown">
          								<li><a href="#">Account Settings</a></li>
          								<li><a href="#">Logout</a></li>
        							</ul>
      							</li>
							</div >
						</div>
					</li>
				</ul>
			</section>
		</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title><%= content_for?(:title) ? yield(:title) : "foundation-rails" %></title>
    <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.8.2/jquery.min.js"></script>
    <script src="http://code.highcharts.com/stock/highstock.js"></script>
    <script src="http://code.highcharts.com/stock/modules/exporting.js"></script>
    
    <%= stylesheet_link_tag    "application", :media => "all" %>
    <%= javascript_include_tag "vendor/modernizr", "application"%>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <%= render "layouts/header" %>
    <%= yield %>
    <%= javascript_include_tag "application" %>
  </body>
</html>

app/views/news/index.html.erb
<div class = "row">
	<h3>News</h3>
	<br />
	<div id = "newscontainer">
		<script language="JavaScript" src="http://feed2js.org//feed2js.php?src=http%3A%2F%2Ffinance.yahoo.com%2Frss%2Fheadline%3Fs%3Dgoog%2Cappl%2Cfb&chan=y&num=20&date=y&targ=y&utf=y&html=a"  charset="UTF-8" type="text/javascript"></script>

		<noscript>
		<a href="http://feed2js.org//feed2js.php?src=http%3A%2F%2Ffinance.yahoo.com%2Frss%2Fheadline%3Fs%3Dgoog%2Cappl%2Cfb&chan=y&num=20&date=y&targ=y&utf=y&html=y">View RSS feed</a>
		</noscript>
	</div>
</div>

app/views/portfolio/add.html.erb
<h1>Portfolio#add</h1>
<p>Find me in app/views/portfolio/add.html.erb</p>

app/views/portfolio/index.html.erb
<%= form_for @new_portfolio, :url => {:action => "add"} do |f| %>
<div class="row">
	<div class="small- 20 columns">
		<div class="row">
			<div class="small-2 columns">
        		<%= f.label :ticker, class: "right inline"%>
		    </div>
			<div class="small-3 columns">
        		<%= f.text_field :ticker, :placeholder =>"Stock Ticker" %>
		    </div>

		    <div class="small-2 columns">
        		<%= f.label :quantity, class: "right inline"%>
		    </div>
		    <div class="small-3 columns">
		    	<%= f.text_field :quantity, :placeholder => "Amount of Stock" %>
		    </div>
		    <div class="small-10 columns">
		    	<%= f.submit "Add Stock", class: "btn btn-primary"%>
		    </div>
		</div>
		<div class="row">
			
		</div>
	</div>
</div>
<% end %>

<table>
  <thead>
    <tr>
      <th width="200">Stock</th>
      <th width="150">Quantity</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><a href="search/goog">GOOG</a></td>
      <td>3</td>
    </tr>
    <tr>
      <td><a href="search/fb">FB</a></td>
      <td>2</td>
    </tr>
    <tr>
      <td><a href="search/aapl">AAPL</a></td>
      <td>7</td>
    </tr>
  </tbody>
</table>

app/views/portfolio/new.html.erb
<h1>Portfolio#new</h1>
<p>Find me in app/views/portfolio/new.html.erb</p>

app/views/portfolio/remove.html.erb
<h1>Portfolio#remove</h1>
<p>Find me in app/views/portfolio/remove.html.erb</p>

app/views/search/aapl.html.erb
<div class="row">
	<div class="row">
		<div class="large-12 columns">
			<h1>  AAPL Historical Data </h1>
		</div>
	</div>
	<div class="large-8 columns">
		<div id="container" style="min-height:500px"></div>
	</div>
	<div class="large-4 columns">

	</div>
</div>

app/views/search/fb.html.erb
<div class="row">
	<div class="row">
		<div class="large-12 columns">
			<h1>  FB Historical Data </h1>
		</div>
	</div>
	<div class="large-8 columns">
		<div id="container3" style="min-height:500px"></div>
	</div>
	<div class="large-4 columns">

	</div>
</div>

app/views/search/goog.html.erb
<div class="row">
	<div class="row">
		<div class="large-12 columns">
			<h1>  Google Historical Data </h1>
		</div>
	</div>
	<div class="large-8 columns">
		<div id="container2" style="min-height:500px"></div>
	</div>
	<div class="large-4 columns">

	</div>
</div>

app/views/search/index.html.erb
<h1>Search#index</h1>
<p>Find me in app/views/search/index.html.erb</p>

app/views/welcome/index.html.erb
<div class="row">
	<div class="row">
		<div class="large-12 columns">
			<h1>  Welcome to Stock Forecaster!</h1>
		</div>
	</div>
	<div class="large-8 columns">
		<div id="container" style="min-height:500px"></div>
	</div>
	<div class="large-4 columns">

	</div>
</div>